"""user expire token

Revision ID: 76ebfd1c28ca
Revises: 9ef70c0d21a0
Create Date: 2021-04-13 02:15:47.481692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ebfd1c28ca'
down_revision = '9ef70c0d21a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expire_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expire_datetime')
    # ### end Alembic commands ###
