"""user name length

Revision ID: 933069309e85
Revises: bcd327797638
Create Date: 2021-04-27 17:38:20.257641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933069309e85'
down_revision = 'bcd327797638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
