"""user name text

Revision ID: 95e49359b02e
Revises: 933069309e85
Create Date: 2021-04-27 17:40:10.116434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e49359b02e'
down_revision = '933069309e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
