"""user salt

Revision ID: 9ef70c0d21a0
Revises: 11e83ae5f7a9
Create Date: 2021-04-08 20:24:45.313239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef70c0d21a0'
down_revision = '11e83ae5f7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build_object', 'contact')
    op.add_column('user', sa.Column('salt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    op.add_column('build_object', sa.Column('contact', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
